# Generated by Django 5.1.6 on 2025-03-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="last_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[("in_progress", "수강 중"), ("completed", "완료"), ("dropped", "수강 취소")],
                default="in_progress",
                max_length=20,
            ),
        ),
    ]
