# Generated by Django 5.1.6 on 2025-03-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0002_enrollment_last_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="progress",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="lessonprogress",
            name="last_watched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
