# Generated by Django 5.1.6 on 2025-03-07 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_role_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifications', models.TextField()),
                ('experience', models.TextField()),
                ('sample_video_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', '대기 중'), ('APPROVED', '승인됨'), ('REJECTED', '거부됨')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
