# Generated by Django 5.1.6 on 2025-03-12 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_instructorapplication"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
