# Generated by Django 5.1.6 on 2025-03-06 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[("draft", "초안"), ("review", "검토 중"), ("published", "출시됨")],
                default="draft",
                max_length=11,
            ),
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("video_url", models.CharField(blank=True, max_length=500, null=True)),
                ("duration", models.PositiveIntegerField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField()),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lessons", to="courses.section"
                    ),
                ),
            ],
        ),
    ]
