# Generated by Django 5.1.6 on 2025-03-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_remove_course_access_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="is_free",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="is_completed",
        ),
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[("review", "심사 중"), ("approved", "승인됨"), ("not_approved", "승인되지 않음")],
                default="review",
                max_length=20,
            ),
        ),
    ]
