# Generated by Django 5.1.6 on 2025-03-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_remove_course_is_free_remove_lesson_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[("review", "심사 중"), ("approved", "승인 완료"), ("not_approved", "수정 필요")],
                default="review",
                max_length=20,
            ),
        ),
    ]
