# Generated by Django 5.1.6 on 2025-03-18 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_alter_course_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["-created_at"]},
        ),
    ]
