# Generated by Django 5.1.6 on 2025-03-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_alter_course_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="avg_rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="course",
            name="thumbnail",
            field=models.ImageField(blank=True, default="default.jpg", null=True, upload_to="courses/"),
        ),
    ]
