# Generated by Django 5.1.6 on 2025-03-11 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0006_remove_course_is_free_remove_lesson_duration_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(verbose_name="문제 내용")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="문제 순서")),
            ],
            options={
                "verbose_name": "문제",
                "verbose_name_plural": "문제 목록",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=200, verbose_name="선택지 내용")),
                ("is_correct", models.BooleanField(default=False, verbose_name="정답 여부")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="quizzes.question",
                        verbose_name="문제",
                    ),
                ),
            ],
            options={
                "verbose_name": "선택지",
                "verbose_name_plural": "선택지 목록",
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="퀴즈 제목")),
                ("description", models.TextField(blank=True, verbose_name="퀴즈 설명")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="courses.course",
                        verbose_name="강의",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_quizzes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="출제자",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="courses.lesson",
                        verbose_name="강의 영상",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="courses.section",
                        verbose_name="섹션",
                    ),
                ),
            ],
            options={
                "verbose_name": "퀴즈",
                "verbose_name_plural": "퀴즈 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="quizzes.quiz",
                verbose_name="퀴즈",
            ),
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(auto_now_add=True, verbose_name="시작 시간")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="완료 시간")),
                ("score", models.PositiveIntegerField(default=0, verbose_name="점수")),
                ("total_questions", models.PositiveIntegerField(default=0, verbose_name="전체 문제 수")),
                ("correct_answers", models.PositiveIntegerField(default=0, verbose_name="정답 수")),
                ("is_completed", models.BooleanField(default=False, verbose_name="완료 여부")),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="quizzes.quiz",
                        verbose_name="퀴즈",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="학생",
                    ),
                ),
            ],
            options={
                "verbose_name": "퀴즈 시도",
                "verbose_name_plural": "퀴즈 시도 목록",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_correct", models.BooleanField(default=False, verbose_name="정답 여부")),
                (
                    "selected_choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selections",
                        to="quizzes.choice",
                        verbose_name="선택한 답",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quizzes.question",
                        verbose_name="문제",
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quizzes.quizattempt",
                        verbose_name="퀴즈 시도",
                    ),
                ),
            ],
            options={
                "verbose_name": "답변",
                "verbose_name_plural": "답변 목록",
                "unique_together": {("attempt", "question")},
            },
        ),
    ]
